import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '30-60-90 Plan',
  description: 'Generated by manual scaffold',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}